#override defaults for dev
version: "3.3"

services:
  app_server:
    environment:
      CONTAINER_UID: __USER_ID__
      APPLICATION_UID: __USER_ID__
      APPLICATION_GID: __GROUP_ID__
    ports:
      - 8000:8000
      - 8080:8080

  app_mysql:
    ports:
      - "4406:3306"
    volumes:
      - ./dev-ops/docker/_volumes/mysql:/mysql-data